# Generated by Django 3.1.7 on 2021-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttxn",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymenttxn",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymenttxn",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default=12121,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
