# Generated by Django 3.1.7 on 2021-10-21 02:21

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20211015_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttxn",
            name="razorpay_response",
            field=jsonfield.fields.JSONField(
                default={}, load_kwargs={"object_pairs_hook": collections.OrderedDict}
            ),
        ),
    ]
