# Generated by Django 3.1.7 on 2021-12-15 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 12, 15, 12, 42, 35, 937924, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pitch",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
