# Generated by Django 3.1.7 on 2022-02-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0007_article"),
    ]

    operations = [
        migrations.DeleteModel(name="FriendRequest",),
    ]
