# Generated by Django 3.1.7 on 2021-10-23 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "cmp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "cfcmp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cap_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small Cap"),
                            ("mid", "Mid Cap"),
                            ("large", "Large Cap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("stocks_bought", models.IntegerField(default=0)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Batsman", "Batsman"),
                            ("Bowler", "Bowler"),
                            ("Batting Allrounder", "Batting Allrounder"),
                            ("Bowling Allrounder", "Bowling Allrounder"),
                        ],
                        max_length=120,
                        null=True,
                    ),
                ),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["cap_type", "code"],},
        ),
        migrations.CreateModel(
            name="CompanyValuations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "mkt_qty",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "cap",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "cmp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cap_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small Cap"),
                            ("mid", "Mid Cap"),
                            ("large", "Large Cap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("stocks_bought", models.IntegerField(default=0)),
                (
                    "current_form",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("team", models.CharField(default="NA", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(default="NA", max_length=100)),
                ("name", models.CharField(default="NA", max_length=50)),
                ("team", models.CharField(default="NA", max_length=50)),
                ("runs", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("matches", models.IntegerField(default=0)),
                ("last_match_pushed", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="CurrentMatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField(default=0)),
                ("home_team", models.CharField(default="NA", max_length=50)),
                ("away_team", models.CharField(default="NA", max_length=50)),
                ("batting_team", models.CharField(default="NA", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(default="NA", max_length=100)),
                ("name", models.CharField(default="NA", max_length=50)),
                ("team", models.CharField(default="NA", max_length=50)),
                ("runs", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("runouts", models.IntegerField(default=0)),
                ("dismissed", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-timestamp", "-updated"],},
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(default="NA", max_length=200)),
                ("dob", models.CharField(default="NA", max_length=50)),
                ("pob", models.CharField(default="NA", max_length=50)),
                ("playing_role", models.CharField(default="NA", max_length=50)),
                ("batting_style", models.CharField(default="NA", max_length=50)),
                ("bowling_style", models.CharField(default="NA", max_length=50)),
                ("ipl_team", models.CharField(default="NA", max_length=50)),
                ("matches", models.IntegerField(default=0)),
                ("batting_innings", models.IntegerField(default=0)),
                ("notouts", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("highest", models.CharField(default="0", max_length=10)),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "batting_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("bowling_innings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("bbi", models.CharField(default="0", max_length=10)),
                ("bbm", models.CharField(default="0", max_length=10)),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bowling_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fourfers", models.IntegerField(default=0)),
                ("fifers", models.IntegerField(default=0)),
                ("tenfers", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PlayerStatsBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(default="NA", max_length=200)),
                ("dob", models.CharField(default="NA", max_length=50)),
                ("pob", models.CharField(default="NA", max_length=50)),
                ("playing_role", models.CharField(default="NA", max_length=50)),
                ("batting_style", models.CharField(default="NA", max_length=50)),
                ("bowling_style", models.CharField(default="NA", max_length=50)),
                ("ipl_team", models.CharField(default="NA", max_length=50)),
                ("matches", models.IntegerField(default=0)),
                ("batting_innings", models.IntegerField(default=0)),
                ("notouts", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("highest", models.CharField(default="0", max_length=10)),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "batting_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("bowling_innings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("bbi", models.CharField(default="0", max_length=10)),
                ("bbm", models.CharField(default="0", max_length=10)),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bowling_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fourfers", models.IntegerField(default=0)),
                ("fifers", models.IntegerField(default=0)),
                ("tenfers", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PlayerStatsODI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(default="NA", max_length=200)),
                ("dob", models.CharField(default="NA", max_length=50)),
                ("pob", models.CharField(default="NA", max_length=50)),
                ("playing_role", models.CharField(default="NA", max_length=50)),
                ("batting_style", models.CharField(default="NA", max_length=50)),
                ("bowling_style", models.CharField(default="NA", max_length=50)),
                ("ipl_team", models.CharField(default="NA", max_length=50)),
                ("matches", models.IntegerField(default=0)),
                ("batting_innings", models.IntegerField(default=0)),
                ("notouts", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("highest", models.CharField(default="0", max_length=10)),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "batting_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("bowling_innings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("bbi", models.CharField(default="0", max_length=10)),
                ("bbm", models.CharField(default="0", max_length=10)),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bowling_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fourfers", models.IntegerField(default=0)),
                ("fifers", models.IntegerField(default=0)),
                ("tenfers", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PlayerStatsTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(default="NA", max_length=200)),
                ("dob", models.CharField(default="NA", max_length=50)),
                ("pob", models.CharField(default="NA", max_length=50)),
                ("playing_role", models.CharField(default="NA", max_length=50)),
                ("batting_style", models.CharField(default="NA", max_length=50)),
                ("bowling_style", models.CharField(default="NA", max_length=50)),
                ("ipl_team", models.CharField(default="NA", max_length=50)),
                ("matches", models.IntegerField(default=0)),
                ("batting_innings", models.IntegerField(default=0)),
                ("notouts", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("highest", models.CharField(default="0", max_length=10)),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "batting_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("bowling_innings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("bbi", models.CharField(default="0", max_length=10)),
                ("bbm", models.CharField(default="0", max_length=10)),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bowling_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fourfers", models.IntegerField(default=0)),
                ("fifers", models.IntegerField(default=0)),
                ("tenfers", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ScoreCard",
            fields=[
                ("cricinfo_id", models.IntegerField(primary_key=True, serialize=False)),
                ("batting_team", models.CharField(default="NA", max_length=50)),
                ("bowling_team", models.CharField(default="NA", max_length=50)),
                ("batsman", models.CharField(default="NA", max_length=50)),
                ("nonstriker", models.CharField(default="NA", max_length=50)),
                ("bowler", models.CharField(default="NA", max_length=50)),
                ("runs_batsman", models.IntegerField(default=0)),
                ("runs_extras", models.IntegerField(default=0)),
                (
                    "extra_type",
                    models.CharField(
                        choices=[
                            (0, "none"),
                            (1, "wides"),
                            (2, "no-ball"),
                            (3, "byes"),
                            (4, "legbyes"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "dismissal_type",
                    models.CharField(
                        choices=[
                            (0, "none"),
                            (1, "caught"),
                            (2, "bowled"),
                            (3, "lbw"),
                            (4, "runout"),
                            (5, "stumped"),
                            (6, "retired-hurt"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("dismissed_batsman", models.CharField(default="NA", max_length=50)),
                ("fielder", models.CharField(default="NA", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UpcomingMatches",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField(default=0)),
                ("home_team", models.CharField(default="NA", max_length=50)),
                ("away_team", models.CharField(default="NA", max_length=50)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AllMatches",
            fields=[
                (
                    "match_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="market.match",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("market.match",),
        ),
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_name", models.CharField(max_length=50)),
                ("stocks", models.ManyToManyField(blank=True, to="market.Company")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserNews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.news"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionScheduler",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("buy", "BUY"), ("sell", "SELL")], max_length=10
                    ),
                ),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("buy", "BUY"), ("sell", "SELL")], max_length=10
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="Sellstage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("order_id", models.IntegerField(default=0)),
                ("sold", models.IntegerField(default=0)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="Sellbook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="PlayerValuations",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("team", models.CharField(default="NA", max_length=50)),
                (
                    "system_valuation",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "current_form",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("mkt_qty", models.IntegerField(default=100000)),
                (
                    "company",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=market.models.get_order_id, max_length=10),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("mode", models.CharField(default="NA", max_length=10)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Placed", "Placed"),
                            ("Pending", "Pending"),
                            ("Order Matched", "Order Mathced"),
                            ("Cancelled", "Cancelled"),
                            ("Failed", "Failed"),
                            ("Completed", "Completed"),
                        ],
                        default="Placed",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=50)),
                (
                    "execution_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "brokerage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="match",
            name="player",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.playerstats",
            ),
        ),
        migrations.CreateModel(
            name="CompletedOrders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=market.models.get_order_id, max_length=10),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("mode", models.CharField(default="NA", max_length=10)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Placed", "Placed"),
                            ("Pending", "Pending"),
                            ("Order Matched", "Order Mathced"),
                            ("Cancelled", "Cancelled"),
                            ("Failed", "Failed"),
                            ("Completed", "Completed"),
                        ],
                        default="Placed",
                        max_length=20,
                    ),
                ),
                (
                    "executionprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "brokerage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="CompanyCMPRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cmp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "cmpchange",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "contextcmp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0 run scored", "0 run scored"),
                            ("1 run scored", "1 run scored"),
                            ("2 runs scored", "2 runs scored"),
                            ("3 runs scored", "3 runs scored"),
                            ("4 runs scored", "4 runs scored"),
                            ("5 runs scored", "5 runs scored"),
                            ("6 runs scored", "6 runs scored"),
                            ("No ball bowled", "No ball bowled"),
                            ("Wide ball bowled", "Wide ball bowled"),
                            ("Bye run scored", "Bye run scored"),
                            ("Clean Bowled", "Clean Bowled"),
                            ("Hit Wicket", "Hit Wicket"),
                            ("Run out", "Run out"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
        migrations.CreateModel(
            name="CancelledOrders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=market.models.get_order_id, max_length=10),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("mode", models.CharField(default="NA", max_length=10)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Placed", "Placed"),
                            ("Pending", "Pending"),
                            ("Order Matched", "Order Mathced"),
                            ("Cancelled", "Cancelled"),
                            ("Failed", "Failed"),
                            ("Completed", "Completed"),
                        ],
                        default="Placed",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(default="Default", max_length=50)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="Buystage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("order_id", models.IntegerField(default=0)),
                ("bought", models.IntegerField(default=0)),
                (
                    "orderprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="Buybook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_stocks", models.IntegerField(default=0)),
                ("first_loading_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_loading_time"],},
        ),
        migrations.CreateModel(
            name="BallbyBall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=500)),
                ("innings_no", models.IntegerField(default=0)),
                ("over_no", models.IntegerField(default=0)),
                ("delivery_no", models.IntegerField(default=0)),
                ("runs_batsman", models.IntegerField(default=0)),
                ("runs_extra", models.IntegerField(default=0)),
                ("extra_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dismissal_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "batsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batsman",
                        to="market.company",
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowler",
                        to="market.company",
                    ),
                ),
                (
                    "dismissed_batsman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_batsman",
                        to="market.company",
                    ),
                ),
                (
                    "fielder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fielder",
                        to="market.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stocks", models.IntegerField(default=0)),
                ("buy_escrow", models.IntegerField(default=0)),
                ("sell_escrow", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "investment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "avgprice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "company")},},
        ),
    ]
