# Generated by Django 3.1.7 on 2021-12-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerStatsBackup", new_name="PlayerStatsT20",
        ),
        migrations.AddField(
            model_name="match",
            name="match_format",
            field=models.CharField(
                choices=[("T20", "T20"), ("ODI", "ODI"), ("Test", "Test")],
                default="T20",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.company",
            ),
        ),
        migrations.DeleteModel(name="PlayerStats",),
    ]
