# Generated by Django 3.1.7 on 2021-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_auto_20211226_1250"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStatsT20Intl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(default="NA", max_length=200)),
                ("dob", models.CharField(default="NA", max_length=50)),
                ("pob", models.CharField(default="NA", max_length=50)),
                ("playing_role", models.CharField(default="NA", max_length=50)),
                ("batting_style", models.CharField(default="NA", max_length=50)),
                ("bowling_style", models.CharField(default="NA", max_length=50)),
                ("ipl_team", models.CharField(default="NA", max_length=50)),
                ("matches", models.IntegerField(default=0)),
                ("batting_innings", models.IntegerField(default=0)),
                ("notouts", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("highest", models.CharField(default="0", max_length=10)),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "batting_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("catches", models.IntegerField(default=0)),
                ("stumpings", models.IntegerField(default=0)),
                ("bowling_innings", models.IntegerField(default=0)),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("bbi", models.CharField(default="0", max_length=10)),
                ("bbm", models.CharField(default="0", max_length=10)),
                (
                    "bowling_average",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bowling_sr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fourfers", models.IntegerField(default=0)),
                ("fifers", models.IntegerField(default=0)),
                ("tenfers", models.IntegerField(default=0)),
                ("espn_link", models.URLField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="playerstatsodi",
            name="espn_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerstatst20",
            name="espn_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerstatstest",
            name="espn_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
