# Generated by Django 3.1.7 on 2021-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_auto_20211226_1333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_format",
            field=models.CharField(
                choices=[
                    ("T20", "T20"),
                    ("T20I", "T20I"),
                    ("ODI", "ODI"),
                    ("Test", "Test"),
                ],
                default="T20",
                max_length=20,
            ),
        ),
    ]
