# Generated by Django 3.1.7 on 2021-10-23 07:33

import accounts.models
import collections
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=20),
                ),
                (
                    "escrow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "loan",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000"), max_digits=20
                    ),
                ),
                ("loan_count", models.IntegerField(default=1)),
                ("loan_count_absolute", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coeff_of_variation",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("mobile", models.CharField(max_length=12, null=True)),
                (
                    "referral_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PotentialUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Invited", "Invited"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                        ],
                        default="Invited",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_users",
                        to=settings.AUTH_USER_MODEL,
                        validators=[accounts.models.validate_potential_user],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Invited", "Invited"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                        ],
                        default="Invited",
                        max_length=20,
                    ),
                ),
                (
                    "to_users",
                    jsonfield.fields.JSONField(
                        default={},
                        load_kwargs={"object_pairs_hook": collections.OrderedDict},
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
