# Generated by Django 3.1.7 on 2021-12-12 15:34

import collections
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="coeff_of_variation",),
        migrations.RemoveField(model_name="user", name="loan",),
        migrations.RemoveField(model_name="user", name="loan_count",),
        migrations.RemoveField(model_name="user", name="loan_count_absolute",),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "documents",
                    jsonfield.fields.JSONField(
                        default={},
                        load_kwargs={"object_pairs_hook": collections.OrderedDict},
                    ),
                ),
                ("is_player", models.BooleanField(default=False)),
                (
                    "player_profile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Batsman", "Batsman"),
                            ("Bowler", "Bowler"),
                            ("Batting Allrounder", "Batting Allrounder"),
                            ("Bowler Allrounder", "Bowler Allrounder"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "referred_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CricTrade Event", "CricTrade Event"),
                            ("Friend Invitation", "Friend Invitation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="accounts/kycfiles/aadhar/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "pancard",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="accounts/kycfiles/pancard/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "passport",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="accounts/kycfiles/passport/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "driving_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="accounts/kycfiles/driving_license/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
