# Generated by Django 3.1.7 on 2021-12-12 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20211212_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="kycfiles",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userfiles",
            ),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="aadhar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="accounts/kycfiles/aadhar/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="driving_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="accounts/kycfiles/driving_license/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="pancard",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="accounts/kycfiles/pancard/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="passport",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="accounts/kycfiles/passport/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
