# Generated by Django 3.1.7 on 2021-12-15 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20211212_2351"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="accounts/profile_pics/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="runs",
            field=models.IntegerField(default=100),
        ),
    ]
