# Generated by Django 3.1.7 on 2021-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20211215_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="_userprofile_followers_+",
                to="accounts.UserProfile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="_userprofile_friends_+",
                to="accounts.UserProfile",
            ),
        ),
    ]
