# Generated by Django 3.1.7 on 2022-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20220118_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialuser",
            name="waitlist_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
