# Generated by Django 3.1.7 on 2022-02-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20220122_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="crickcoins",
            field=models.IntegerField(default=1000),
        ),
    ]
