# Generated by Django 3.1.7 on 2021-10-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Entertainment Subscriptions",
                                "Entertainment Subscriptions",
                            ),
                            ("Apparel & Accessories", "Apparel & Accessories"),
                            ("Food & Beverage", "Food & Beverage"),
                            ("Mobile & Electronics", "Mobile & Electronics"),
                            ("Health & Wellness", "Health & Wellness"),
                            ("Magazines Subscriptions", "Magazines Subscriptions"),
                            ("Cabs & Travels", "Cabs & Travels"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="brandlogos/%Y/%m/%d"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("validity", models.DateTimeField()),
                (
                    "offer_type",
                    models.CharField(
                        blank=True, choices=[("", "")], max_length=100, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtualcoins.brand",
                    ),
                ),
            ],
        ),
    ]
