# Generated by Django 3.1.7 on 2021-12-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0004_auto_20211229_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksDatabasePointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StocksDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company')),
            ],
            options={
                'ordering': ['company', 'pointer'],
                'unique_together': {('company', 'pointer')},
            },
        ),
    ]
